Add a .gitignore rule for .vscode folder
edamame852/opengl-sandbox pull request #4
Opened 2024-05-25 05:51 UTC by slee2879

This adds a line of rule to ignore ``.vscode`` directory.
The directory is [generated by ``VSCode`` to store workspace-specific(also user-specific) configurations.](https://code.visualstudio.com/docs/editor/workspaces#_workspace-tasks-and-launch-configurations)
Since this is not a file we ever need to add to our repo, we might as well just ignore it early on to mitigate potential accidents.

Closes #1

2024-05-25 14:51 UTC, edamame852 commented
Ya, let's just keep on following this format and leave our comments here before merging to main

Since you're designing our .gitignore file
I suggest you update our .gitignore file to [this](https://www.bing.com/search?pglt=43&q=.gitignore+for+C%2B%2B&cvid=feac2f56c50648ec8b1608d6b097d709&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDMzNThqMGoxqAIAsAIA&FORM=ANNTA1&PC=SCOOBE)

That way it will up to standard

2024-05-25 14:52 UTC, edamame852 commented
Also I will need to spend more time on my web application because I ran into some deployment issues that I have absolutely no clue how to slove

2024-05-25 14:52 UTC, edamame852 requested changes
Add more content to the .gitignore file

2024-05-30 10:22 UTC, edamame852 commented
Yo, if you don't update the gitignore file by this week I will add it and merge it myself

2024-05-31 03:53 UTC, slee2879 commented
> Ya, let's just keep on following this format and leave our comments here before merging to main
> 
> Since you're designing our .gitignore file I suggest you update our .gitignore file to [this](https://www.bing.com/search?pglt=43&q=.gitignore+for+C%2B%2B&cvid=feac2f56c50648ec8b1608d6b097d709&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDMzNThqMGoxqAIAsAIA&FORM=ANNTA1&PC=SCOOBE)
> 
> That way it will up to standard

The link doesn't lead me to any specific `.gitignore`, and I believe you already chose `.gitignore` list for `c++` when starting this repo. Could you clarify your demands?

2024-05-31 05:24 UTC, edamame852 commented
Oh I might have sent you the wrong link. In that case let me update you.

2024-05-31 14:41 UTC, edamame852 approved these changes

2024-05-31 14:42 UTC, merged